global:
  resolve_timeout: 10s

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 10s
  receiver: 'default'

receivers:
  - name: 'default'
    # Example: Send alerts to email
    email_configs:
      - to: 'sujalsharma151@gmail.com'
        from: 'techsharma53@gmail.com'
        smarthost: 'smtp.gmail.com:587'
        auth_username: 'techsharma53@gmail.com'
        auth_password: 'csvdmvyncmjovwwx'

groups:
  - name: container-alerts
    rules:
      - alert: HighCPUUsage
        expr: 100 *  (rate(process_cpu_system_seconds_total[1m])) > 5
        for: 10s
        labels:
          severity: warning
        annotations:
          summary: "High CPU Usage Detected"
          description: "CPU usage of container is above 50%. Value: {{ $value }}%"
