
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      # Mount the Prometheus configuration file
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      # Persist Prometheus data
      - prometheus-data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
    restart: unless-stopped
    depends_on:
      - alertmanager  # Prometheus will notify Alertmanager
    networks:
      - monitoring-network

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    ports:
      - "9093:9093"
    volumes:
      # Mount the Alertmanager configuration file
      - ./alertmanager:/alertmanager
    command:
      - "--config.file=/etc/alertmanager/alertmanager.yml"
    restart: unless-stopped
    networks:
      - monitoring-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      # Persist Grafana configuration and data
      - grafana-data:/var/lib/grafana
    environment:
      # Default credentials for Grafana
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    restart: unless-stopped
    networks:
      - monitoring-network

volumes:
  prometheus-data:
    driver: local
  grafana-data:
    driver: local

networks:
  monitoring-network:
    driver: bridge
