global:
  scrape_interval: 15s


alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093  # Connect Prometheus to Alertmanager    
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
      - targets: ['backend.python.com']   
      - targets: ['backend.nodejs.com']