{
 "title": "Flask python backend",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "cpu process total",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 9, "x": 0, "y": 0 },
   "targets": [
    { "expr": "process_cpu_seconds_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "process virtual memory bytes",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 9, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "process_virtual_memory_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "process open fds",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "process_open_fds", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "request count created",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "request_count_created{endpoint=\"/metrics\",method=\"GET\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "process max fds",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 10, "x": 14, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "process_max_fds ", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "request total count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "request_count_total{endpoint=\"/metrics\",method=\"GET\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "total request count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "request_count_total{endpoint=\"/<short_code>\",method=\"GET\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}